spring:
  config:
    activate:
      on-profile: dev
  application:
    name: gymCRM
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always
  logging:
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %logger{36} - [transactionId:%X{transactionId}] %msg%n'
  actuator:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  actuator:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always
---
spring:
  config:
    activate:
      on-profile: test
  actuator:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      health:
        show-details: always
